### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by crownedgrouse** [comment]
Thanks for those usual French typos on English words ;)..
But please remove commit about erlang.mk as I'm not the maintainer.
Propose a PR on erlang.mk repo instead. Otherwise typo will come back on next update...

**Comment by kianmeng** [comment]
> Propose a PR on erlang.mk repo instead. Otherwise typo will come back on next update...

Done. https://github.com/ninenines/erlang.mk/pull/946

**Comment by crownedgrouse** [comment]
Thanks for this PR.

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
